background: ./assets/bg.png
avatar: ./assets/avatar.jpg

menu:
  - name: blog
    title: Blog
    url: Hugo-Blog/
    icon: ./assets/icons/archives.svg
  - name: github
    title: GitHub
    url: https://github.com/Ri-Nai
    icon: ./assets/icons/github.svg
  - name: email
    title: Email
    url: mailto:Ri_Nai_@outlook.com
    icon: ./assets/icons/email.svg
  - name: bilibili
    title: Bilibili
    url: https://space.bilibili.com/4151993
    icon: ./assets/icons/brand-bilibili.svg
  - name: steam
    title: Steam
    url: https://steamcommunity.com/id/Reina__/
    icon: ./assets/icons/steam.svg
